#server:
#  port: 8888
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#    gateway:
#      routes: #数组形式
#        - id: location-manage  #路由唯一标识
#        #uri: http://127.0.0.1:8000  #想要转发到的地址
#          uri: lb://location-manage  # 从nacos获取名称转发,lb是负载均衡轮训策略
#
#          predicates: #断言 配置哪个路径才转发
#            - Path=/manage/**
#          filters: #过滤器，请求在传递过程中通过过滤器修改
#            - StripPrefix=1 #去掉第一层前缀
#
#        - id: location-position  #路由唯一标识
#          #uri: http://127.0.0.1:8000  #想要转发到的地址
#          uri: lb://location-position  # 从nacos获取名称转发,lb是负载均衡轮训策略
#
#          predicates: #断言 配置哪个路径才转发
#            - Path=/position/**
#          filters: #过滤器，请求在传递过程中通过过滤器修改
#            - StripPrefix=1 #去掉第一层前缀
#
#      discovery:
#        locator:
#          enabled: true  #开启网关拉取nacos的服务
#
### 访问路径 http://localhost:8888/order-server/api/v1/video_order/list